# Generated by Django 2.2.1 on 2019-08-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(blank=True, max_length=255, null=True)),
                ('app_password', models.CharField(blank=True, max_length=255, null=True)),
                ('app_a', models.CharField(blank=True, max_length=255, null=True)),
                ('app_b', models.CharField(blank=True, db_column='app-b', max_length=255, null=True)),
                ('app_c', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'app',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('lowyer', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('fax', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('regtime', models.DateField(blank=True, null=True)),
                ('licensecard', models.CharField(blank=True, max_length=200, null=True)),
                ('sheng', models.CharField(blank=True, max_length=200, null=True)),
                ('shi', models.CharField(blank=True, max_length=200, null=True)),
                ('qu', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('isdelete', models.IntegerField(blank=True, null=True)),
                ('cweb', models.CharField(blank=True, max_length=200, null=True)),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyQu',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('qu', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'company_qu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanySheng',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sheng', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'company_sheng',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyShi',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('shi', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'company_shi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword_name', models.CharField(max_length=255)),
                ('keyword_class', models.CharField(blank=True, max_length=255, null=True)),
                ('keywprd_years', models.IntegerField(blank=True, null=True)),
                ('keyword_price', models.FloatField(blank=True, null=True)),
                ('keyword_newdate', models.CharField(blank=True, max_length=255, null=True)),
                ('keyword_date', models.CharField(blank=True, max_length=255, null=True)),
                ('keyword_apply_state', models.IntegerField(blank=True, db_column='Keyword_apply_state', null=True)),
                ('keyword_check_state', models.IntegerField(blank=True, null=True)),
                ('keyword_use_state', models.IntegerField(blank=True, null=True)),
                ('keyword_app_state', models.IntegerField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('isdelete', models.IntegerField(blank=True, null=True)),
                ('keyword_c', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lianxiren',
            fields=[
                ('lxid', models.AutoField(primary_key=True, serialize=False)),
                ('lxname', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('fax', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'lianxiren',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prepayment',
            fields=[
                ('preid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(blank=True, max_length=200, null=True)),
                ('finacetype', models.CharField(blank=True, db_column='finaceType', max_length=200, null=True)),
                ('finacemoney', models.FloatField(blank=True, null=True)),
                ('idbalance', models.FloatField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prepayment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rizhi',
            fields=[
                ('rzid', models.AutoField(primary_key=True, serialize=False)),
                ('rzname', models.CharField(blank=True, max_length=200, null=True)),
                ('rztext', models.TextField(blank=True, null=True)),
                ('rztime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rizhi',
                'managed': False,
            },
        ),
    ]
