# Generated by Django 2.2.1 on 2019-08-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppTb',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=255)),
                ('anumber', models.IntegerField()),
            ],
            options={
                'db_table': 'app_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomertypeTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cstmtype', models.CharField(db_column='cstmType', max_length=100)),
                ('state', models.IntegerField()),
                ('isdelete', models.IntegerField()),
            ],
            options={
                'db_table': 'customertype_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dscttype', models.CharField(db_column='dsctType', max_length=100)),
                ('dsctyear', models.IntegerField(db_column='dsctYear')),
                ('realyear', models.IntegerField(db_column='realYear')),
                ('state', models.IntegerField()),
                ('isdelete', models.IntegerField()),
            ],
            options={
                'db_table': 'discount_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinaceTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finacetype', models.CharField(db_column='finaceType', max_length=50)),
                ('state', models.IntegerField()),
                ('isdelete', models.IntegerField()),
            ],
            options={
                'db_table': 'finace_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LicenseTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licstype', models.CharField(db_column='licsType', max_length=100)),
                ('state', models.IntegerField()),
                ('isdelete', models.IntegerField()),
            ],
            options={
                'db_table': 'license_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServinceTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svctype', models.CharField(db_column='svcType', max_length=100)),
                ('money', models.CharField(max_length=255)),
                ('state', models.IntegerField()),
                ('caozuo', models.IntegerField()),
            ],
            options={
                'db_table': 'servince_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SerYearTb',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ser_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ser_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ser_year_tb',
                'managed': False,
            },
        ),
    ]
