# Generated by Django 2.1.8 on 2019-08-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_header', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'org_pic',
                'managed': False,
            },
        ),
    ]
